services:
  - type: web
    name: flask-server
    env: python
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: DB_HOST
        value: tu_host
      - key: DB_USER
        value: tu_usuario
      - key: DB_PASSWORD
        value: tu_contraseña
      - key: DB_NAME
        value: tu_basededatos
      - key: DB_PORT
        value: "3306"
